"use client";

import React, { useState } from "react";
import { HelpCircle, Send, BookOpen } from "lucide-react";

export default function AskLoopPage() {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<string | null>(null);
  const [sources, setSources] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!question.trim()) return;

    setLoading(true);
    // Mock response after 1 second
    setTimeout(() => {
      setAnswer(
        "Users are generally happy with the new dashboard interface, noting that it is fast and beautiful. However, several users are running into issues with the sign-up and onboarding process. Specifically, verification emails get stuck, requiring multiple page refreshes."
      );
      setSources([
        {
          id: "1",
          content: "The sign up flow gets stuck on verification. Had to refresh three times.",
          channel: "Support ticket"
        },
        {
          id: "2",
          content: "Excellent performance, dashboard loads super fast now! Love the new UI.",
          channel: "App store review"
        }
      ]);
      setLoading(false);
    }, 1000);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Intro Header */}
      <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-6 text-center space-y-2">
        <HelpCircle className="w-10 h-10 text-blue-500 mx-auto" />
        <h2 className="text-xl font-bold text-white">Ask LOOP Intelligence</h2>
        <p className="text-sm text-zinc-450 max-w-lg mx-auto">
          Ask any plain-English question about customer feedback. Answers are generated by Claude AI and grounded strictly in the feedback database.
        </p>
      </div>

      {/* Question Form */}
      <form onSubmit={handleSubmit} className="flex gap-4">
        <input
          type="text"
          placeholder="e.g., What are users saying about the onboarding process?"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          className="flex-1 bg-zinc-900 border border-zinc-800 rounded-lg px-4 py-3 text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500"
        />
        <button
          type="submit"
          disabled={loading}
          className="bg-blue-600 hover:bg-blue-750 text-white rounded-lg px-6 py-3 font-semibold text-sm flex items-center gap-2 transition-all disabled:opacity-50"
        >
          {loading ? "Thinking..." : "Ask"} <Send className="w-4 h-4" />
        </button>
      </form>

      {/* Answer & Sources Panel */}
      {answer && (
        <div className="space-y-6">
          {/* Answer Card */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-6 space-y-4">
            <h3 className="text-sm font-semibold text-zinc-400 uppercase tracking-wider">Answer</h3>
            <p className="text-sm text-zinc-100 leading-6">{answer}</p>
          </div>

          {/* Sources Section */}
          <div className="space-y-3">
            <h4 className="text-sm font-semibold text-zinc-400 flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-blue-500" /> Grounded Feedback Sources
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {sources.map((src, index) => (
                <div key={src.id} className="bg-zinc-900 border border-zinc-805 rounded-lg p-4 space-y-2">
                  <div className="flex justify-between items-center text-xs">
                    <span className="text-blue-400 font-semibold">Source #{index + 1}</span>
                    <span className="text-zinc-500">{src.channel}</span>
                  </div>
                  <p className="text-xs text-zinc-350 italic">"{src.content}"</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
