"use client";

import React, { useState } from "react";
import { HelpCircle, Send, BookOpen } from "lucide-react";

export default function AskLoopPage() {
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<string | null>(null);
  const [sources, setSources] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!question.trim()) return;

    setLoading(true);
    setAnswer(null);
    setSources([]);
    try {
      const res = await fetch("/api/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question }),
      });
      if (res.ok) {
        const data = await res.json();
        setAnswer(data.answer);
        setSources(data.contextUsed || []);
      } else {
        setAnswer("Failed to synthesize response. Please try again later.");
      }
    } catch (err) {
      console.error("Ask AI error", err);
      setAnswer("Network error. Could not connect to LOOP AI services.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Intro Header */}
      <div className="glass-card rounded-2xl p-8 text-center space-y-3 relative overflow-hidden">
        <div className="pointer-events-none absolute -top-10 left-1/2 -translate-x-1/2 h-32 w-32 rounded-full bg-blue-500/20 blur-2xl" />
        <div className="h-14 w-14 rounded-2xl bg-blue-500/10 border border-blue-500/30 flex items-center justify-center mx-auto shadow-[0_0_20px_rgba(59,130,246,0.3)]">
          <HelpCircle className="w-7 h-7 text-blue-400" />
        </div>
        <h2 className="text-2xl font-extrabold text-white tracking-tight">Ask LOOP Intelligence</h2>
        <p className="text-sm text-zinc-400 max-w-lg mx-auto leading-relaxed">
          Ask any plain-English question about customer feedback. Answers are generated by AI and grounded strictly in your feedback database.
        </p>
      </div>

      {/* Question Form */}
      <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-3">
        <input
          type="text"
          placeholder="e.g., What are users saying about the onboarding process?"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          className="glass-input flex-1 rounded-2xl px-5 py-3.5 text-sm placeholder-zinc-500"
        />
        <button
          type="submit"
          disabled={loading}
          className="glass-button rounded-2xl px-7 py-3.5 font-bold text-sm text-white flex items-center justify-center gap-2 shadow-lg disabled:opacity-50"
        >
          {loading ? "Thinking..." : "Ask AI"} <Send className="w-4 h-4" />
        </button>
      </form>

      {/* Answer & Sources Panel */}
      {answer && (
        <div className="space-y-6 animate-fadeIn">
          {/* Answer Card */}
          <div className="glass-card rounded-2xl p-6 space-y-3 border-l-4 border-l-blue-500 relative overflow-hidden">
            <h3 className="text-xs font-bold text-blue-400 uppercase tracking-wider">AI Generated Synthesis</h3>
            <p className="text-sm text-zinc-100 leading-relaxed font-normal">{answer}</p>
          </div>

          {/* Sources Section */}
          <div className="space-y-3">
            <h4 className="text-xs font-bold uppercase tracking-wider text-zinc-400 flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-blue-400" /> Grounded Feedback Sources
            </h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {sources.map((src, index) => (
                <div key={src.id} className="glass-card rounded-xl p-4 space-y-2">
                  <div className="flex justify-between items-center text-xs">
                    <span className="text-blue-400 font-bold">Source #{index + 1}</span>
                    <span className="glass-pill px-2 py-0.5 rounded text-[11px] font-mono text-zinc-400">{src.channel}</span>
                  </div>
                  <p className="text-xs text-zinc-300 italic leading-relaxed">"{src.content}"</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
